### ISSUE TITLE
Please remove this Step from the Worfklow Editor

### ISSUE THREAD

**Issue by fritzfr** [bitrise-io/steps-deploy-to-itunesconnect-shenzhen#7]
If it is deprecated since September 2018, why on earth can I still select it in the workflow editor, just to find out 20 minutes later that my build fails?

Also, consider updating the following post and remove Shenzen from it, as this is the first result from google when searching how to deploy to testflight: https://discuss.bitrise.io/t/how-to-deploy-to-itunes-connect-testflight/780

**Comment by bitce** [comment]
Hi @felix-voicehub! 

Sorry about the inconvenience, and thanks for raising the problem. The step should indeed be hidden from the step library, it is now available due to a recent issue as a result of the workflow editor changes.

The root cause was identified and the fix will shortly follow, thanks again for the report!
